- name: Ensure this is Red Hat
  assert:
    that: "ansible_distribution == 'RedHat'"
  tags:
    - rhsm

- name: Configure Red Hat Subscription Manager
  template:
    src: rhsm.conf.j2
    dest: /etc/rhsm/rhsm.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - rhsm
    - rhsm_rhsm

- import_tasks: "{{ rhsm_method | default('portal') }}.yml"
  tags:
    - rhsm
